### PR TITLE
Fix the 'to Rust Search Extension' button display error

### LINKED ISSUE #216: Wrong crate is added when the crate name does not match the lib name.
I wanted to add [md-5](https://crates.io/crates/md-5) crate whose [lib name is md5](https://github.com/RustCrypto/hashes#crate-names) but actually added [md5](https://crates.io/crates/md5) crate with the version number of md-5.

### PR DESCRIPTION
**Pull request by shwin0901**
Close #216

### CODE REVIEW

File: extension/script/docs-rs.js [hunk 1]
```diff
@@ -91,6 +91,11 @@ document.addEventListener("DOMContentLoaded", async () => {
         // Query installed crates from chrome.storage API
         let crates = await storage.getItem("crates") || {};
         let crate = crates[crateName];
+        if(!crate && crates[targetCrateName]) {
```
Comment (Folyd) [inline extension/script/docs-rs.js:94]: How about:
```js
let crate = crates[crateName] || crates[targetCrateName];
```

**Review by Folyd — CHANGES_REQUESTED** [review]

File: extension/script/docs-rs.js (hunk 1 above)
Comment (shwin0901) [reply extension/script/docs-rs.js:94]: The creatName will be used here:
`await CrateDocManager.removeCrate(crateName)`
